import type { Badge } from '@/lib/types'

export const mockBadges: Badge[] = [
  // --- EARNED BADGES (10) ---
  {
    id: 'badge-1',
    name: 'Bước Đầu Tiên',
    description: 'Ghi nhận hoạt động đầu tiên trong ứng dụng. Hành trình ngàn dặm bắt đầu từ một bước chân.',
    category: 'challenge',
    icon: '👟',
    color: 'text-green-600',
    earnedAt: '2024-01-15T10:30:00.000Z',
    requirement: 'Ghi nhận 1 hoạt động đầu tiên',
    points: 50,
  },
  {
    id: 'badge-2',
    name: 'Nghìn Bước',
    description: 'Đi đủ 1.000 bước trong một ngày. Cột mốc đầu tiên trên con đường chinh phục sức khỏe.',
    category: 'distance',
    icon: '🚶',
    color: 'text-blue-600',
    earnedAt: '2024-01-16T18:00:00.000Z',
    requirement: 'Đi đủ 1.000 bước trong một ngày',
    points: 100,
  },
  {
    id: 'badge-3',
    name: 'Chinh Phục Đầu Tiên',
    description: 'Hoàn thành thử thách đầu tiên. Bạn đã chứng minh rằng mình có thể làm được!',
    category: 'challenge',
    icon: '🏆',
    color: 'text-yellow-600',
    earnedAt: '2024-02-28T23:59:00.000Z',
    requirement: 'Hoàn thành 1 thử thách',
    points: 200,
  },
  {
    id: 'badge-4',
    name: 'Siêu Sao 7 Ngày',
    description: 'Duy trì streak 7 ngày liên tiếp. Bạn đã tạo ra thói quen vận động nhất quán.',
    category: 'streak',
    icon: '⭐',
    color: 'text-orange-500',
    earnedAt: '2024-01-22T20:00:00.000Z',
    requirement: 'Duy trì streak 7 ngày liên tiếp',
    points: 150,
  },
  {
    id: 'badge-5',
    name: 'Người Chạy',
    description: 'Chạy bộ tổng cộng 50km. Đôi chân của bạn ngày càng mạnh mẽ hơn!',
    category: 'distance',
    icon: '🏃',
    color: 'text-green-700',
    earnedAt: '2024-02-15T09:00:00.000Z',
    requirement: 'Chạy bộ tổng cộng 50km',
    points: 300,
  },
  {
    id: 'badge-6',
    name: 'Bạn Đồng Hành',
    description: 'Tham gia thử thách đồng đội đầu tiên. Sức mạnh đến từ sự đoàn kết!',
    category: 'social',
    icon: '🤝',
    color: 'text-blue-500',
    earnedAt: '2024-03-01T08:00:00.000Z',
    requirement: 'Tham gia 1 thử thách đồng đội',
    points: 100,
  },
  {
    id: 'badge-7',
    name: 'Người Đa Năng',
    description: 'Thực hiện 5 loại hoạt động khác nhau. Bạn không bị giới hạn bởi một môn thể thao!',
    category: 'special',
    icon: '🎯',
    color: 'text-purple-600',
    earnedAt: '2024-03-10T15:00:00.000Z',
    requirement: 'Thực hiện 5 loại hoạt động khác nhau',
    points: 200,
  },
  {
    id: 'badge-8',
    name: 'Dậy Sớm',
    description: 'Ghi nhận 10 hoạt động trước 7 giờ sáng. Buổi sáng sớm là của những người chiến thắng!',
    category: 'special',
    icon: '🌅',
    color: 'text-amber-500',
    earnedAt: '2024-03-20T06:45:00.000Z',
    requirement: 'Ghi nhận 10 hoạt động trước 7:00 sáng',
    points: 250,
  },
  {
    id: 'badge-9',
    name: 'Thiên Lý Mã',
    description: 'Tích lũy 1.000km tổng khoảng cách. Một hành trình đáng tự hào!',
    category: 'distance',
    icon: '🐎',
    color: 'text-indigo-600',
    earnedAt: '2024-04-05T12:00:00.000Z',
    requirement: 'Tích lũy 1.000km tổng khoảng cách',
    points: 500,
  },
  {
    id: 'badge-10',
    name: 'Thủ Lĩnh Nhóm',
    description: 'Giúp đội của bạn đứng trong top 3 bảng xếp hạng đồng đội. Bạn là người dẫn dắt!',
    category: 'social',
    icon: '👑',
    color: 'text-yellow-500',
    earnedAt: '2024-04-15T23:59:00.000Z',
    requirement: 'Giúp đội đứng trong top 3 bảng xếp hạng',
    points: 350,
  },

  // --- LOCKED BADGES (8) ---
  {
    id: 'badge-11',
    name: 'Siêu Sao 30 Ngày',
    description: 'Duy trì streak 30 ngày liên tiếp không nghỉ. Chỉ những ai thực sự kiên định mới đạt được.',
    category: 'streak',
    icon: '🌟',
    color: 'text-yellow-400',
    earnedAt: undefined,
    requirement: 'Duy trì streak 30 ngày liên tiếp',
    points: 500,
  },
  {
    id: 'badge-12',
    name: 'Siêu Sao 100 Ngày',
    description: 'Streak 100 ngày liên tiếp. Đây là huy hiệu của những huyền thoại.',
    category: 'streak',
    icon: '💫',
    color: 'text-yellow-300',
    earnedAt: undefined,
    requirement: 'Duy trì streak 100 ngày liên tiếp',
    points: 2000,
  },
  {
    id: 'badge-13',
    name: 'Vận Động Viên Marathon',
    description: 'Chạy bộ tổng cộng 500km. Bạn đã chạy một marathon nhiều lần rồi!',
    category: 'distance',
    icon: '🏅',
    color: 'text-red-500',
    earnedAt: undefined,
    requirement: 'Chạy bộ tổng cộng 500km',
    points: 1000,
  },
  {
    id: 'badge-14',
    name: 'Chinh Phục 5 Thử Thách',
    description: 'Hoàn thành 5 thử thách khác nhau. Bạn đang trở thành một chiến binh thực sự!',
    category: 'challenge',
    icon: '🎖️',
    color: 'text-emerald-600',
    earnedAt: undefined,
    requirement: 'Hoàn thành 5 thử thách',
    points: 750,
  },
  {
    id: 'badge-15',
    name: 'Cộng Đồng Năng Động',
    description: 'Được 10 người khác tham gia thử thách cùng bạn. Bạn truyền cảm hứng cho người khác!',
    category: 'social',
    icon: '🌍',
    color: 'text-teal-500',
    earnedAt: undefined,
    requirement: 'Có 10 người tham gia thử thách cùng bạn',
    points: 400,
  },
  {
    id: 'badge-16',
    name: 'Triệu Bước Chân',
    description: 'Tích lũy 1.000.000 bước tổng cộng. Triệu bước, triệu kỉ niệm!',
    category: 'distance',
    icon: '👣',
    color: 'text-green-500',
    earnedAt: undefined,
    requirement: 'Tích lũy 1.000.000 bước tổng cộng',
    points: 800,
  },
  {
    id: 'badge-17',
    name: 'Sức Khỏe Hoàn Hảo',
    description: 'Đốt cháy hơn 100.000 kcal tổng cộng. Cơ thể bạn cảm ơn bạn mỗi ngày!',
    category: 'special',
    icon: '💎',
    color: 'text-cyan-500',
    earnedAt: undefined,
    requirement: 'Đốt cháy tổng cộng 100.000 kcal',
    points: 1500,
  },
  {
    id: 'badge-18',
    name: 'Vô Địch Toàn Quốc',
    description: 'Đứng số 1 bảng xếp hạng toàn nền tảng trong ít nhất 1 tuần. Không ai sánh được!',
    category: 'special',
    icon: '🥇',
    color: 'text-yellow-600',
    earnedAt: undefined,
    requirement: 'Đứng số 1 bảng xếp hạng toàn nền tảng 1 tuần',
    points: 3000,
  },
]
