import type { Challenge } from '@/lib/types'

export const mockChallenges: Challenge[] = [
  {
    id: 'challenge-1',
    title: 'Tháng 4 — Triệu Bước Chân',
    description: 'Thử thách đi bộ 1 triệu bước trong tháng 4. Hãy cùng nhau xây dựng thói quen vận động mỗi ngày và cải thiện sức khỏe toàn diện!',
    type: 'steps',
    status: 'active',
    startDate: '2026-04-01T00:00:00.000Z',
    endDate: '2026-04-30T23:59:59.000Z',
    target: 1000000,
    unit: 'bước',
    organizationId: 'org-1',
    participantCount: 1248,
    maxParticipants: 2000,
    prizeDescription: 'Top 10 nhận thẻ quà tặng VinMart 500.000đ + huy hiệu đặc biệt',
    rules: [
      'Hoạt động được ghi nhận từ 00:00 ngày 01/04/2026',
      'Mỗi ngày có thể ghi tối đa 3 hoạt động',
      'Số bước phải được xác nhận qua ứng dụng hoặc thiết bị đeo tay',
      'Không chấp nhận dữ liệu từ thiết bị giả mạo',
    ],
    isTeamChallenge: false,
    createdBy: 'user-2',
    coverGradient: 'from-green-400 to-emerald-600',
  },
  {
    id: 'challenge-2',
    title: 'Chinh Phục 100km — Đội Hình',
    description: 'Thử thách đồng đội: Mỗi đội 5 người cùng chinh phục 100km trong 3 tuần. Tổng khoảng cách của tất cả thành viên được tính vào mục tiêu chung.',
    type: 'team_steps',
    status: 'active',
    startDate: '2026-04-08T00:00:00.000Z',
    endDate: '2026-04-28T23:59:59.000Z',
    target: 100,
    unit: 'km',
    organizationId: 'org-1',
    participantCount: 350,
    maxParticipants: 500,
    prizeDescription: 'Đội vô địch nhận phần thưởng trị giá 2.000.000đ + bữa ăn team',
    rules: [
      'Mỗi đội gồm đúng 5 thành viên',
      'Khoảng cách từ tất cả loại hoạt động di chuyển đều được tính',
      'Thành viên có thể tham gia nhiều đội khác nhau',
      'Kết quả được cập nhật mỗi 6 giờ',
    ],
    isTeamChallenge: true,
    teamSize: 5,
    createdBy: 'user-2',
    coverGradient: 'from-blue-400 to-indigo-600',
  },
  {
    id: 'challenge-3',
    title: 'Đốt Cháy Calo — Tháng 5',
    description: 'Thử thách đốt cháy 30.000 kcal trong tháng 5. Mọi hoạt động thể chất đều được tính. Hãy bắt đầu chuẩn bị ngay từ bây giờ!',
    type: 'calories',
    status: 'upcoming',
    startDate: '2026-05-01T00:00:00.000Z',
    endDate: '2026-05-31T23:59:59.000Z',
    target: 30000,
    unit: 'kcal',
    organizationId: 'org-1',
    participantCount: 423,
    maxParticipants: 1500,
    prizeDescription: 'Top 5 nhận phiếu mua sắm Adidas trị giá 1.000.000đ',
    rules: [
      'Đăng ký trước ngày 30/04/2026',
      'Calories được tính tự động theo loại hoạt động và thời lượng',
      'Cần ghi lại ít nhất 1 hoạt động mỗi tuần để duy trì tư cách tham gia',
      'Kết quả sẽ được kiểm tra ngẫu nhiên',
    ],
    isTeamChallenge: false,
    createdBy: 'user-2',
    coverGradient: 'from-orange-400 to-red-600',
  },
  {
    id: 'challenge-4',
    title: 'Chạy Bộ Sáng Sớm — 21 Ngày',
    description: 'Xây dựng thói quen chạy bộ mỗi sáng trong 21 ngày liên tiếp. Mỗi buổi tối thiểu 30 phút. Cùng nhau tạo nên lối sống khỏe mạnh!',
    type: 'duration',
    status: 'upcoming',
    startDate: '2026-05-05T00:00:00.000Z',
    endDate: '2026-05-25T23:59:59.000Z',
    target: 630,
    unit: 'phút',
    organizationId: 'org-2',
    participantCount: 187,
    maxParticipants: 300,
    prizeDescription: 'Tất cả người hoàn thành nhận huy hiệu "Người Chạy Bền" + 500 điểm thưởng',
    rules: [
      'Hoạt động phải là chạy bộ hoặc đi bộ nhanh',
      'Mỗi ngày phải ghi ít nhất 30 phút',
      'Được phép bỏ tối đa 2 ngày trong 21 ngày',
      'Hoạt động cần ghi trong vòng 2 giờ sau khi kết thúc',
    ],
    isTeamChallenge: false,
    createdBy: 'user-5',
    coverGradient: 'from-purple-400 to-pink-600',
  },
  {
    id: 'challenge-5',
    title: 'Tháng 3 — Đại Chiến Bước Chân',
    description: 'Thử thách lớn nhất quý 1: 800.000 bước trong tháng 3. Hơn 500 nhân viên đã tham gia và kết thúc thành công!',
    type: 'steps',
    status: 'completed',
    startDate: '2026-03-01T00:00:00.000Z',
    endDate: '2026-03-31T23:59:59.000Z',
    target: 800000,
    unit: 'bước',
    organizationId: 'org-1',
    participantCount: 568,
    prizeDescription: 'Top 3 đã nhận thẻ quà tặng 1.000.000đ mỗi người',
    rules: [
      'Mọi hoạt động đều được tính',
      'Số bước tích lũy trong suốt tháng',
      'Không giới hạn số hoạt động mỗi ngày',
    ],
    isTeamChallenge: false,
    createdBy: 'user-2',
    coverGradient: 'from-teal-400 to-cyan-600',
  },
  {
    id: 'challenge-6',
    title: 'Yoga Tâm Bình — 30 Ngày',
    description: 'Thử thách thực hành yoga 30 ngày liên tiếp. Mỗi buổi tối thiểu 20 phút. Tìm lại sự cân bằng trong cuộc sống bận rộn.',
    type: 'duration',
    status: 'completed',
    startDate: '2026-02-01T00:00:00.000Z',
    endDate: '2026-03-02T23:59:59.000Z',
    target: 600,
    unit: 'phút',
    organizationId: 'org-3',
    participantCount: 234,
    prizeDescription: 'Người hoàn thành nhận huy hiệu "Thiền Sư" + voucher spa 300.000đ',
    rules: [
      'Chỉ tính hoạt động yoga và thiền',
      'Tối thiểu 20 phút mỗi ngày',
      'Ảnh checkin không bắt buộc nhưng được khuyến khích',
    ],
    isTeamChallenge: false,
    createdBy: 'user-7',
    coverGradient: 'from-violet-400 to-purple-600',
  },
  {
    id: 'challenge-7',
    title: 'Thể Thao Hè 2026 — Bản Nháp',
    description: 'Dự án thử thách mùa hè sắp được triển khai. Thử thách tổng hợp kết hợp nhiều loại hình thể thao trong 2 tháng hè.',
    type: 'distance',
    status: 'draft',
    startDate: '2026-06-01T00:00:00.000Z',
    endDate: '2026-07-31T23:59:59.000Z',
    target: 200,
    unit: 'km',
    organizationId: 'org-1',
    participantCount: 0,
    prizeDescription: 'Phần thưởng đang được lên kế hoạch',
    rules: [
      'Quy tắc đang được soạn thảo',
    ],
    isTeamChallenge: false,
    createdBy: 'user-2',
    coverGradient: 'from-yellow-400 to-amber-600',
  },
  {
    id: 'challenge-8',
    title: 'Grand Challenge — Vươn Tới Đỉnh Cao',
    description: 'Thử thách flagship của WellnessRace: 5.000.000 bước trong 60 ngày. Dành cho những người thực sự nghiêm túc với sức khỏe. Giải thưởng giá trị nhất trong năm!',
    type: 'steps',
    status: 'active',
    startDate: '2026-04-01T00:00:00.000Z',
    endDate: '2026-05-31T23:59:59.000Z',
    target: 5000000,
    unit: 'bước',
    organizationId: 'org-1',
    participantCount: 892,
    maxParticipants: 1000,
    prizeDescription: 'Vô địch: Tour du lịch Đà Lạt cho 2 người (trị giá 10.000.000đ). Top 2-5: Đồng hồ thể thao Garmin. Top 6-10: Thẻ gym 6 tháng.',
    rules: [
      'Mở cho tất cả nhân viên FPT Software',
      'Dữ liệu phải được đồng bộ từ thiết bị đeo tay hoặc app sức khỏe',
      'Gian lận dữ liệu sẽ bị loại vĩnh viễn',
      'Ban tổ chức có quyền kiểm tra và xác minh dữ liệu bất kỳ lúc nào',
      'Kết quả chính thức công bố trong vòng 7 ngày sau khi kết thúc',
    ],
    isTeamChallenge: false,
    createdBy: 'user-2',
    coverGradient: 'from-rose-400 via-pink-500 to-purple-600',
  },
]
