import type { LeaderboardEntry } from '@/lib/types'

export const individualLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    previousRank: 2,
    userId: 'user-2',
    name: 'Trần Văn Hùng',
    avatar: 'https://ui-avatars.com/api/?name=Tran+Van+Hung&background=1A73E8&color=fff&size=128',
    organizationId: 'org-1',
    teamId: 'team-1',
    teamName: 'FPT Eagles',
    totalPoints: 18750,
    totalSteps: 3124800,
    totalKm: 2183.4,
    activeDays: 87,
    delta: 1,
  },
  {
    rank: 2,
    previousRank: 1,
    userId: 'user-5',
    name: 'Hoàng Thị Hoa',
    avatar: 'https://ui-avatars.com/api/?name=Hoang+Thi+Hoa&background=9C27B0&color=fff&size=128',
    organizationId: 'org-2',
    teamId: 'team-3',
    teamName: 'Vingroup Warriors',
    totalPoints: 16340,
    totalSteps: 2890300,
    totalKm: 2023.2,
    activeDays: 82,
    delta: -1,
  },
  {
    rank: 3,
    previousRank: 4,
    userId: 'user-1',
    name: 'Nguyễn Thị Lan',
    avatar: 'https://ui-avatars.com/api/?name=Nguyen+Thi+Lan&background=008C44&color=fff&size=128',
    organizationId: 'org-1',
    teamId: 'team-1',
    teamName: 'FPT Eagles',
    totalPoints: 15420,
    totalSteps: 2847500,
    totalKm: 1987.3,
    activeDays: 79,
    delta: 1,
  },
  {
    rank: 4,
    previousRank: 3,
    userId: 'user-8',
    name: 'Bùi Văn Nam',
    avatar: 'https://ui-avatars.com/api/?name=Bui+Van+Nam&background=F44336&color=fff&size=128',
    organizationId: 'org-4',
    teamId: 'team-5',
    teamName: 'TCB Runners',
    totalPoints: 14200,
    totalSteps: 2456700,
    totalKm: 1719.7,
    activeDays: 76,
    delta: -1,
  },
  {
    rank: 5,
    previousRank: 6,
    userId: 'user-4',
    name: 'Phạm Minh Tuấn',
    avatar: 'https://ui-avatars.com/api/?name=Pham+Minh+Tuan&background=FF5722&color=fff&size=128',
    organizationId: 'org-2',
    teamId: 'team-3',
    teamName: 'Vingroup Warriors',
    totalPoints: 13890,
    totalSteps: 2654900,
    totalKm: 1858.4,
    activeDays: 74,
    delta: 1,
  },
  {
    rank: 6,
    previousRank: 5,
    userId: 'user-10',
    name: 'Đinh Văn Khoa',
    avatar: 'https://ui-avatars.com/api/?name=Dinh+Van+Khoa&background=607D8B&color=fff&size=128',
    organizationId: 'org-5',
    teamId: 'team-6',
    teamName: 'VNG Coders',
    totalPoints: 12100,
    totalSteps: 2234100,
    totalKm: 1563.9,
    activeDays: 70,
    delta: -1,
  },
  {
    rank: 7,
    previousRank: 9,
    userId: 'user-7',
    name: 'Đặng Thị Ngọc',
    avatar: 'https://ui-avatars.com/api/?name=Dang+Thi+Ngoc&background=4CAF50&color=fff&size=128',
    organizationId: 'org-3',
    teamId: 'team-4',
    teamName: 'Masan Tigers',
    totalPoints: 11560,
    totalSteps: 2123400,
    totalKm: 1486.4,
    activeDays: 68,
    delta: 2,
  },
  {
    rank: 8,
    previousRank: 7,
    userId: 'user-3',
    name: 'Lê Thị Mai',
    avatar: 'https://ui-avatars.com/api/?name=Le+Thi+Mai&background=E91E63&color=fff&size=128',
    organizationId: 'org-1',
    teamId: 'team-2',
    teamName: 'FPT Phoenix',
    totalPoints: 10230,
    totalSteps: 1956200,
    totalKm: 1368.3,
    activeDays: 65,
    delta: -1,
  },
  {
    rank: 9,
    previousRank: 8,
    userId: 'user-12',
    name: 'Phan Văn Đức',
    avatar: 'https://ui-avatars.com/api/?name=Phan+Van+Duc&background=3F51B5&color=fff&size=128',
    organizationId: 'org-1',
    teamId: 'team-2',
    teamName: 'FPT Phoenix',
    totalPoints: 11020,
    totalSteps: 2078300,
    totalKm: 1454.8,
    activeDays: 66,
    delta: -1,
  },
  {
    rank: 10,
    previousRank: 11,
    userId: 'user-9',
    name: 'Ngô Thị Thu',
    avatar: 'https://ui-avatars.com/api/?name=Ngo+Thi+Thu&background=FF9800&color=fff&size=128',
    organizationId: 'org-4',
    totalPoints: 9450,
    totalSteps: 1834500,
    totalKm: 1284.2,
    activeDays: 60,
    delta: 1,
  },
  {
    rank: 11,
    previousRank: 10,
    userId: 'user-ext-1',
    name: 'Lý Thị Bảo Châu',
    avatar: 'https://ui-avatars.com/api/?name=Ly+Thi+Bao+Chau&background=00ACC1&color=fff&size=128',
    organizationId: 'org-2',
    totalPoints: 9120,
    totalSteps: 1780000,
    totalKm: 1246.0,
    activeDays: 58,
    delta: -1,
  },
  {
    rank: 12,
    previousRank: 14,
    userId: 'user-6',
    name: 'Vũ Đức Thịnh',
    avatar: 'https://ui-avatars.com/api/?name=Vu+Duc+Thinh&background=00BCD4&color=fff&size=128',
    organizationId: 'org-3',
    teamId: 'team-4',
    teamName: 'Masan Tigers',
    totalPoints: 8970,
    totalSteps: 1743600,
    totalKm: 1220.5,
    activeDays: 56,
    delta: 2,
  },
  {
    rank: 13,
    previousRank: 12,
    userId: 'user-ext-2',
    name: 'Trương Quốc Bảo',
    avatar: 'https://ui-avatars.com/api/?name=Truong+Quoc+Bao&background=8BC34A&color=fff&size=128',
    organizationId: 'org-4',
    totalPoints: 8740,
    totalSteps: 1698400,
    totalKm: 1188.9,
    activeDays: 55,
    delta: -1,
  },
  {
    rank: 14,
    previousRank: 15,
    userId: 'user-11',
    name: 'Trịnh Thị Linh',
    avatar: 'https://ui-avatars.com/api/?name=Trinh+Thi+Linh&background=795548&color=fff&size=128',
    organizationId: 'org-5',
    teamId: 'team-6',
    teamName: 'VNG Coders',
    totalPoints: 8640,
    totalSteps: 1678900,
    totalKm: 1175.2,
    activeDays: 54,
    delta: 1,
  },
  {
    rank: 15,
    previousRank: 13,
    userId: 'user-ext-3',
    name: 'Cao Thị Minh Tú',
    avatar: 'https://ui-avatars.com/api/?name=Cao+Thi+Minh+Tu&background=EC407A&color=fff&size=128',
    organizationId: 'org-1',
    totalPoints: 8320,
    totalSteps: 1623000,
    totalKm: 1136.1,
    activeDays: 52,
    delta: -2,
  },
  {
    rank: 16,
    previousRank: 16,
    userId: 'user-ext-4',
    name: 'Nguyễn Hoàng Long',
    avatar: 'https://ui-avatars.com/api/?name=Nguyen+Hoang+Long&background=5C6BC0&color=fff&size=128',
    organizationId: 'org-2',
    totalPoints: 7980,
    totalSteps: 1545600,
    totalKm: 1082.0,
    activeDays: 50,
    delta: 0,
  },
  {
    rank: 17,
    previousRank: 18,
    userId: 'user-ext-5',
    name: 'Đinh Thị Phương',
    avatar: 'https://ui-avatars.com/api/?name=Dinh+Thi+Phuong&background=26A69A&color=fff&size=128',
    organizationId: 'org-3',
    totalPoints: 7650,
    totalSteps: 1487200,
    totalKm: 1041.0,
    activeDays: 48,
    delta: 1,
  },
  {
    rank: 18,
    previousRank: 17,
    userId: 'user-ext-6',
    name: 'Lê Minh Hiếu',
    avatar: 'https://ui-avatars.com/api/?name=Le+Minh+Hieu&background=FFA726&color=fff&size=128',
    organizationId: 'org-5',
    totalPoints: 7420,
    totalSteps: 1440800,
    totalKm: 1008.6,
    activeDays: 47,
    delta: -1,
  },
  {
    rank: 19,
    previousRank: 20,
    userId: 'user-ext-7',
    name: 'Trần Thị Hương',
    avatar: 'https://ui-avatars.com/api/?name=Tran+Thi+Huong&background=AB47BC&color=fff&size=128',
    organizationId: 'org-1',
    totalPoints: 7110,
    totalSteps: 1381500,
    totalKm: 967.1,
    activeDays: 45,
    delta: 1,
  },
  {
    rank: 20,
    previousRank: 19,
    userId: 'user-ext-8',
    name: 'Vương Đức Anh',
    avatar: 'https://ui-avatars.com/api/?name=Vuong+Duc+Anh&background=EF5350&color=fff&size=128',
    organizationId: 'org-4',
    totalPoints: 6870,
    totalSteps: 1334700,
    totalKm: 934.3,
    activeDays: 43,
    delta: -1,
  },
]

export const teamLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    previousRank: 2,
    userId: 'team-1',
    name: 'FPT Eagles',
    avatar: 'https://ui-avatars.com/api/?name=FPT+Eagles&background=FF6600&color=fff&size=128',
    organizationId: 'org-1',
    teamId: 'team-1',
    teamName: 'FPT Eagles',
    totalPoints: 52400,
    totalSteps: 9876500,
    totalKm: 6913.6,
    activeDays: 88,
    delta: 1,
  },
  {
    rank: 2,
    previousRank: 1,
    userId: 'team-3',
    name: 'Vingroup Warriors',
    avatar: 'https://ui-avatars.com/api/?name=Vingroup+Warriors&background=003087&color=fff&size=128',
    organizationId: 'org-2',
    teamId: 'team-3',
    teamName: 'Vingroup Warriors',
    totalPoints: 48750,
    totalSteps: 9234100,
    totalKm: 6463.9,
    activeDays: 85,
    delta: -1,
  },
  {
    rank: 3,
    previousRank: 3,
    userId: 'team-5',
    name: 'TCB Runners',
    avatar: 'https://ui-avatars.com/api/?name=TCB+Runners&background=E31837&color=fff&size=128',
    organizationId: 'org-4',
    teamId: 'team-5',
    teamName: 'TCB Runners',
    totalPoints: 39200,
    totalSteps: 7465800,
    totalKm: 5226.1,
    activeDays: 80,
    delta: 0,
  },
  {
    rank: 4,
    previousRank: 5,
    userId: 'team-2',
    name: 'FPT Phoenix',
    avatar: 'https://ui-avatars.com/api/?name=FPT+Phoenix&background=FF6600&color=fff&size=128',
    organizationId: 'org-1',
    teamId: 'team-2',
    teamName: 'FPT Phoenix',
    totalPoints: 35670,
    totalSteps: 6812300,
    totalKm: 4768.6,
    activeDays: 76,
    delta: 1,
  },
  {
    rank: 5,
    previousRank: 4,
    userId: 'team-4',
    name: 'Masan Tigers',
    avatar: 'https://ui-avatars.com/api/?name=Masan+Tigers&background=C41E3A&color=fff&size=128',
    organizationId: 'org-3',
    teamId: 'team-4',
    teamName: 'Masan Tigers',
    totalPoints: 32180,
    totalSteps: 6134700,
    totalKm: 4294.3,
    activeDays: 72,
    delta: -1,
  },
  {
    rank: 6,
    previousRank: 6,
    userId: 'team-6',
    name: 'VNG Coders',
    avatar: 'https://ui-avatars.com/api/?name=VNG+Coders&background=0065BD&color=fff&size=128',
    organizationId: 'org-5',
    teamId: 'team-6',
    teamName: 'VNG Coders',
    totalPoints: 28940,
    totalSteps: 5523400,
    totalKm: 3866.4,
    activeDays: 68,
    delta: 0,
  },
]
