import type { Team } from '@/lib/types'

export const mockTeams: Team[] = [
  {
    id: 'team-1',
    name: 'FPT Eagles',
    organizationId: 'org-1',
    members: ['user-1', 'user-2', 'user-ext-9', 'user-ext-10', 'user-ext-11'],
    captainId: 'user-2',
    totalPoints: 52400,
    rank: 1,
    previousRank: 2,
    avatarColor: '#FF6600',
  },
  {
    id: 'team-2',
    name: 'FPT Phoenix',
    organizationId: 'org-1',
    members: ['user-3', 'user-12', 'user-ext-12', 'user-ext-13', 'user-ext-14'],
    captainId: 'user-12',
    totalPoints: 35670,
    rank: 4,
    previousRank: 5,
    avatarColor: '#E91E63',
  },
  {
    id: 'team-3',
    name: 'Vingroup Warriors',
    organizationId: 'org-2',
    members: ['user-4', 'user-5', 'user-ext-15', 'user-ext-16', 'user-ext-17'],
    captainId: 'user-5',
    totalPoints: 48750,
    rank: 2,
    previousRank: 1,
    avatarColor: '#003087',
  },
  {
    id: 'team-4',
    name: 'Masan Tigers',
    organizationId: 'org-3',
    members: ['user-6', 'user-7', 'user-ext-18', 'user-ext-19', 'user-ext-20'],
    captainId: 'user-7',
    totalPoints: 32180,
    rank: 5,
    previousRank: 4,
    avatarColor: '#C41E3A',
  },
  {
    id: 'team-5',
    name: 'TCB Runners',
    organizationId: 'org-4',
    members: ['user-8', 'user-9', 'user-ext-3', 'user-ext-21', 'user-ext-22'],
    captainId: 'user-8',
    totalPoints: 39200,
    rank: 3,
    previousRank: 3,
    avatarColor: '#E31837',
  },
  {
    id: 'team-6',
    name: 'VNG Coders',
    organizationId: 'org-5',
    members: ['user-10', 'user-11', 'user-ext-23', 'user-ext-24', 'user-ext-25'],
    captainId: 'user-10',
    totalPoints: 28940,
    rank: 6,
    previousRank: 6,
    avatarColor: '#0065BD',
  },
]
